spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/secudoc
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.secudoc.user_service.dto.UserRegisteredEvent
    listener:
      missing-topics-fatal: false

server:
  port: 8082
  
  